version: '3.1'
services:
  delivery-service:
    image: betulcetinkaya/delivery-service:${TAG}
    container_name: delivery-service
    env_file: docker-compose.env
    ports:
      - 8084:8084
    networks:
        - services
networks:
  services:
    external:
      name: services
