version: '3.1'
services:
  delivery-service:
    image: docker.pkg.github.com/betulcetinkaya/delivery-service/${IMAGE_NAME}:${TAG}
    container_name: delivery-service
    env_file: docker-compose.env
    ports:
      - 8084:8084
    networks:
        - services
networks:
  services:
    external:
      name: services
